name: CI Delivery
on:
  push:
    branches:
      - main

jobs:
  build_iOS:
    name: Build for iOS
    runs-on: macos-11
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.5.1'

      - name: Checks-out my repository
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version:  '2.2.3'

      - name: Download Flutter packages
        run: flutter pub get
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Import Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n ${{ secrets.PROVISIONING_PROFILE }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/main.mobileprovision

      - name: Import Code-Signing Certificates
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: Create ipa file
        run: flutter build ipa --export-options-plist=ExportOptions.plist --build-number ${GITHUB_RUN_NUMBER}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios
          path: ./build/ios/ipa/bay_life.ipa

      - name: Upload to AppStoreConnect
        run: xcrun altool --upload-app -f "./build/ios/ipa/bay_life.ipa" -u "${{ secrets.APPLE_ID }}" -p "${{ secrets.APPLE_APP_PASS }}"

      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: build_app
          SLACK_TITLE: Delivary Success! MAKUHARI Bay Life
          SLACK_COLOR: good

      - name: Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: build_app
          SLACK_TITLE: Delivary Failure! MAKUHARI Bay Life
          SLACK_COLOR: danger
